version: '3.8'
services:
  api:
      build:
        context: ./.docker/php/8.1
        dockerfile: Dockerfile
        args:
          WWWGROUP: '${WWWGROUP}'
      extra_hosts:
        - 'host.docker.internal:host-gateway'
      ports:
        - '${APP_PORT:-80}:80'
      environment:
        WWWUSER: '${WWWUSER}'
        LARAVEL_SAIL: 1
        XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
        XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
      volumes:
        - '.:/var/www/html'
      networks:
        - backend
      depends_on:
        - pgsql

  pgsql:
      image: 'postgres:13'
      ports:
        - '${FORWARD_DB_PORT:-5432}:5432'
      environment:
        PGPASSWORD: '${DB_PASSWORD:-secret}'
        POSTGRES_DB: '${DB_DATABASE}'
        POSTGRES_USER: '${DB_USERNAME}'
        POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
      volumes:
        - 'pgsql:/var/lib/postgresql/data'
      networks:
        - backend
      healthcheck:
        test: ["CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}"]
        retries: 3
        timeout: 5s

networks:
  backend:
    driver: bridge
volumes:
  pgsql:
    driver: local
